### ISSUE TITLE
is:issue is:open Dear author,please tell me the files argument contens tow pdf,or jpg,or ohter format?

### ISSUE THREAD

**Issue by ushio20** [fbonnier/file_comparison#1]

**Comment by fbonnier** [comment]
Hi, this project is supposed to compare Neo (https://neo.readthedocs.io/en/stable/) compatible files and Numpy files (https://numpy.org/doc/stable/index.html).
There are also some algorithms able to compare any file by bytes, but you will only get a score, you will not get the differences between the files.
